version: '2'
services:
  web:
    container_name: meta
    build: .
    depends_on:
      - solr
    ports:
      - "80:80"
    links:
      - solr
  solr:
    container_name: solr
    build: solr
    ports:
      - "8983:8983"